import Link from "next/link";
import TodoSection from "../../components/TodoSection";

export default async function UserDashboard({
  params }: { params: { userId: string }}) {
    const userId = params.userId;

  return (
    <div className="container mx-auto px-4 py-8">
      <main className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <p>This page is generated by Server-Side Rendering.</p>
        <p>The user ID is {userId}.</p>
        <TodoSection />
        {/*
        <WeatherSection />
        <GallerySection />
        <CalendarSection /> */}
        <Link href="/">
          <p>Home</p>
        </Link>
      </main>
    </div>
  );
}
