// import { GetStaticProps, NextPage } from "next";
import Link from "next/link";

// type SSGProps = {
//   message: string;
// };

export const metadata = {
  title: "SSG Page",
  description: "This page is generated by Static Site Generation.",
};

export default async function SSG() {
  const timestamp = new Date().toLocaleString();
  const message = `The current time is ${timestamp}.`;

  console.log(message);

  return (
    <div>
      <main>
        <div>
          <p>This page is generated by Static Site Generation.</p>
          <p>{message}</p>
          <Link href="/">Home</Link>
        </div>
      </main>
    </div>
  );
}
