import { GetStaticProps, NextPage } from 'next';

type SSGProps = {
  message: string;
}

export const metadata = {
  title: 'SSG Page',
  description: 'This page is generated by Static Site Generation.',
};

export default async function SSG() {

  const timestamp = new Date().toLocaleString();
  const message = `The current time is ${timestamp}.`;

  console.log(message);

  return (
    <div>
      <main>
        <p>
          This page is generated by Static Site Generation.
        </p>
        <p>
          {message}
        </p>
      </main>
    </div>
  )
}